version: '3.8'
services:
    app:
        container_name: acg-supply-station
        image: acg-supply-station:v1.0.1
        restart: always
        network_mode: host
        # privileged: true # 如果需要访问主机的网络，可以取消注释这一行
        environment:
            - TZ=Asia/Shanghai # 设置时区为北京时间
        volumes:
            - /home/docker/acg-supply-station/logs:/app/logs
            - /home/docker/acg-supply-station/appsetting.json:/app/appsetting.json
            - /etc/ssl/private:/etc/ssl/private
            - /home/docker/acg-supply-station/images:/app/wwwroot/images 
