/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFoot: typeof import('./src/components/AppFoot.vue')['default']
    AppHead: typeof import('./src/components/AppHead.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImagesContainer: typeof import('./src/components/ImagesContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
